---
name: $(Build.BuildId)
pool:
  vmImage: 'ubuntu-16.04'
trigger:
  - master
steps:
  - task: UseDotNet@2
    displayName: "Use .NET Core sdk 2.2"
    inputs:
      packageType: sdk
      version: 2.2.207

  - bash: |
      set -eu -o pipefail
      sudo pip install awscli
      export AWS_SECRET_ACCESS_KEY=$(AWS_SECRET_ACCESS_KEY)
      chmod +x ./pipeline.sh
      ./pipeline.sh $(Build.BuildId) $(System.DefaultWorkingDirectory)
    displayName: Pipeline Bash Script
    enabled: true

  - task: PublishBuildArtifacts@1
    displayName: "Publish Artifact: manifests"
    inputs:
      PathtoPublish: k8s
      ArtifactName: manifests

  - task: PublishTestResults@2
    displayName: Publish Test Results
    inputs:
      testRunner: VSTest
      testResultsFiles: testresults.trx
      searchFolder: '$(System.DefaultWorkingDirectory)/output'
    condition: succeededOrFailed()

  - task: PublishCodeCoverageResults@1
    displayName: 'Publish code coverage'
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: '$(System.DefaultWorkingDirectory)/output/coverage.cobertura.xml'
