apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: iamroleservice
  namespace: $(kubernetes-namespace)
  labels:
    project: selfservice
    department: devex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iamroleservice
  template:
    metadata:
      labels:
        app: iamroleservice
        project: selfservice
        department: devex
    spec:
      containers:
        - name: iamroleservice
          image: 579478677147.dkr.ecr.eu-central-1.amazonaws.com/ded/iamroleservice:$(Build.BuildId)
          ports:
            - containerPort: 80
              name: web
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: iamroleservice
                  key: aws-access-key-id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: iamroleservice
                  key: aws-secret-access-key
            - name: AWS_REGION
              value: $(AWS_REGION)