---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: iamsync
  namespace: $(kubernetes-namespace)
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iamsync
  template:
    metadata:
      labels:
        app: iamsync
    spec:
      containers:
        - name: iamsymc
          image: 579478677147.dkr.ecr.eu-central-1.amazonaws.com/ded/iamsync:$(Build.BuildId)
          ports:
            - containerPort: 80
              name: web
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          env:
            - name: awesome
              value: "yes"
