apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: iamroleservice
  namespace: $(kubernetes-namespace)
  labels:
    project: selfservice
    department: devex
    app: iamroleservice
    component: iamroleservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iamroleservice
  template:
    metadata:
      labels:
        app: iamroleservice
        project: selfservice
        department: devex
      annotations:
        iam.amazonaws.com/role: iamroleservice
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
    spec:
      containers:
      - name: iamroleservice
        image: 579478677147.dkr.ecr.eu-central-1.amazonaws.com/ded/iamroleservice:$(Build.BuildId)
        ports:
        - containerPort: 80
          name: web
        - containerPort: 8080
          name: metrics
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        livenessProbe:
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 5
          httpGet:
            port: web
            path: /healthz
        readinessProbe:
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 5
          httpGet:
            port: web
            path: /healthz
        env:
        - name: AWS_REGION
          value: $(AWS_REGION)
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: $(KAFKA_BOOTSTRAP_SERVERS)
        - name: KAFKA_BROKER_VERSION_FALLBACK
          value: "0.10.0.0"
        - name: KAFKA_API_VERSION_FALLBACK_MS
          value: "0"
        - name: KAFKA_SASL_USERNAME
          value: $(KAFKA_SASL_USERNAME)
        - name: KAFKA_SASL_PASSWORD
          value: $(KAFKA_SASL_PASSWORD)
        - name: KAFKA_GROUP_ID
          value: "$(KAFKA_GROUP_ID)"
        - name: KAFKA_ENABLE_AUTO_COMMIT
          value: "false"
        - name: KAFKA_SASL_MECHANISMS
          value: "PLAIN"
        - name: KAFKA_SECURITY_PROTOCOL
          value: "SASL_SSL"

        
          
