---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: iamsync
  namespace: $(kubernetes-namespace)
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.rule.type: PathPrefixStrip
spec:
  rules:
    - host: app.dfds.cloud
      http:
        paths:
          - path: /iamsync
            backend:
              serviceName: iamsync
              servicePort: external
