apiVersion: v1
kind: Secret
metadata:
  name: aws-janitor-kafka-credentials
  namespace: $(kubernetes-namespace)
  labels:
    project: selfservice
    department: devex
    app: team-service
type: Opaque
stringData:
  username: "$(KAFKA_SASL_USERNAME)"
  password: "$(KAFKA_SASL_PASSWORD)"
