---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: iamsync
  name: iamsync
  namespace: $(kubernetes-namespace)
spec:
  ports:
    - name: external
      port: 80
      targetPort: web
  selector:
    app: iamsync
  type: ClusterIP
