---
apiVersion: v1
kind: Service
metadata:
  name: iamroleservice
  namespace: $(kubernetes-namespace)
  labels:
    app: iamroleservice
    project: selfservice
    department: devex
spec:
  ports:
    - name: external
      port: 80
      targetPort: web
  selector:
    app: iamroleservice
  type: ClusterIP
