---
apiVersion: v1
kind: Service
metadata:
  name: aws-janitor
  namespace: $(kubernetes-namespace)
  labels:
    app: aws-janitor
    component: aws-janitor
    project: selfservice
    department: devex
spec:
  ports:
    - name: external
      port: 80
      targetPort: web
  selector:
    app: aws-janitor
  type: ClusterIP
