swagger: '2.0'
info:
  version: 0.0.1
  title: IAM Role Service
  description: Small service for creating IAM roles in AWS
consumes:
  - application/json
produces:
  - application/json
basePath: /api
paths:
  /roles:
    post:
      summary: Creates a single role
      parameters: 
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              name: 
                type: string
      responses:
        200: 
          description: OK