---
swagger: '2.0'
info:
  version: 0.0.1
  title: IAM Role Service
  description: Small service for creating IAM roles in AWS
consumes:
  - application/json
produces:
  - application/json
basePath: /api
paths:
  /roles:
    post:
      summary: Creates a single role
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: "#/definitions/CreateIAMRoleRequest"
      responses:
        200:
          description: The IAM role was created.
        400:
          description: The role name is invalid.
        500:
          description: An error occured trying to create the IAM role.
definitions:
  CreateIAMRoleRequest:
    type: object
    properties:
      name:
        type: string
